project_name: docsonnet
before:
  hooks:
    - go mod tidy
builds:
  - binary: docsonnet
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
checksum:
  name_template: 'checksums.txt'
dockers:
- image_templates:
  - "ghcr.io/jsonnet-libs/docsonnet:{{ .Version }}-amd64"
  use: buildx
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/amd64"
- image_templates:
  - "ghcr.io/jsonnet-libs/docsonnet:{{ .Version }}-arm64v8"
  use: buildx
  goarch: arm64
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/arm64/v8"
docker_manifests:
- name_template: ghcr.io/jsonnet-libs/docsonnet:{{ .Version }}
  image_templates:
  - ghcr.io/jsonnet-libs/docsonnet:{{ .Version }}-amd64
  - ghcr.io/jsonnet-libs/docsonnet:{{ .Version }}-arm64v8
